# Use CVXPy to solve capital asset pricing model

Here we will seek to solve the capital asset pricing model using CVXPY. To formulate the problem, we will consider Problem 3.3.1 from Shreve which states:

Given an initial wealth $X_{0}$, find an adapted porfolio process $\Delta_{0}, \Delta_{1}...\Delta_{N-1}$ that maximises the utility function
\begin{equation}
\mathbb{E} U(X_{N})\,,
\end{equation}
subject to the wealth equation
\begin{equation}
X_{n+1} = \Delta_{n}S_{n+1} + (1+r)(X_{n} - \Delta_{n}S_{n})
\end{equation}
where $\mathbb{E}$ is the expectation take with respect to the real underlying distribution of the market, and $U(X_{N})$ is the utility function of the final wealth.

As is shown in the text, this problem can be recast as a simpler problem with relation to the state prices of the asses such that we have the following recasting:

Find a vector $\vec{x}$ that maximises $\sum_{n} p_{n}U(x_{n})$ subject to $\sum_{n} p_{n} \zeta_{n} x_{n} = X_{0}$, where $\zeta_{n}$ is the state price given by 
\begin{equation}
    \zeta_{n} = \frac{Z(\omega_{1}\omega_{2}...\omega_{N})}{(1+r)^{N}}\,,
\end{equation}
where $Z = \tilde{\mathbb{P}}/{\mathbb{P}}$ is the Randon-Nikdoynm derivative of the risk neutral probabilty with respect to the actual underlying probability distribution.

Given the symmetries of the Binomial asset pricing model, we can improve efficiency of the calculation by exploiting these symmetries.
This is that the probabilities of different permutations are equal e.g $P(HT) = P(TH)$, which also extends to the risk neutral probabilities, and the the state prices $\zeta$


In [1]:
import cvxpy as cp
import numpy as np
from scipy.special import binom

# Here we will use the functionality of the binomial asset tree
from Binomial_asset_tree import binomial_tree_european, Capital_asset_pricing

In [2]:
def calculate_Sn(S0, u, n):
    # Compute potential price outcomes
    return S0 * (1/u) ** (np.arange(n, -1, -1)) * u ** (np.arange(0, n + 1, 1))

In [5]:
n = 2
u = 2
r = 0.25

risk_p = np.array([1/4, 2/4, 1/4])
p = np.array([1/9, 4/9, 4/9])
Z = risk_p/p
zeta = Z/(1+r)**2
pn_zeta = p*zeta
X0 = 4
Sn = calculate_Sn(X0, u, n-1)

params = {'r': r,
         'u': u,
         'd': 1/u,
         'X0': X0,
         'p': p,
         'n': n}

model = Capital_asset_pricing(params)

model.solve()
# print(risk_p)
# print(p)

In [12]:
model.x.value

array([1.38888888, 5.55555556, 5.55555556])

In [13]:
x = cp.Variable(n+1)
prob = cp.Problem(cp.Maximize(p@cp.log(x)), [pn_zeta@x==X0])
prob.solve()

1.9458474871352984

In [14]:
x.value

array([ 2.77777912,  5.55555311, 11.11111464])

In [206]:
# Define some system parameters for the model
u = 2
p = 0.5

N = 2
n = 2
K = 7
S0 = 4
r = 0.25

risk_p = (1 + r - 1/u)/(u-1/u)

# Compute real probs
real_probs = (1-p) ** (np.arange(n, -1, -1)) * (p) ** (np.arange(0, n + 1, 1)) *  binom(n, np.arange(n+1))
# real_probs = np.array([1/9, 4/9, 4/9])
print(real_probs)

risk_probs = (risk_p) ** (np.arange(n, -1, -1)) * (1-risk_p) ** (np.arange(0, n + 1, 1)) *  binom(n, np.arange(n+1))
print(risk_probs)
Z = risk_probs/real_probs

zeta = Z/(1+r)**(2)
pn_zeta = real_probs*zeta
Sn = calculate_Sn(S0, u, n)

[0.25 0.5  0.25]
[0.25 0.5  0.25]


In [207]:
x = cp.Variable(n+1)
prob = cp.Problem(cp.Maximize(real_probs@cp.log(x)), [pn_zeta@x==X0])
prob.solve()

1.8325814628517012

In [208]:
x.value

array([6.25001158, 6.24998841, 6.25001158])

array([0.46065971, 3.68527804, 7.37055299])

# 2/

In [15]:
binom(n, np.arange9)

ValueError: invalid number of arguments